feat!: add script for check json

diff --git a/.github/workflows/checker.yml b/.github/workflows/checker.yml
--- a/.github/workflows/checker.yml
+++ b/.github/workflows/checker.yml
@@ -53,3 +53,14 @@ jobs:
         uses: actions/checkout@v6
         with:
           fetch-depth: 0
+
+      - name: Validate info.json files
+        run: |
+          set +e
+          output=$(python3 .github/workflows/checker_scipt.py 2>&1)
+          status=$?
+          echo "$output"
+          if [ $status -ne 0 ]; then
+            echo "JSON validation failed"
+            exit $status
+          fi
